### PR TITLE
update and clean up config to API v3

### PR DESCRIPTION
**Pull request by coby2023t**
update and clean up config to API v3
got problem pulling po files from transifex, the docs and sample config did not apply to the APIv3, that confused new comer

### CODE REVIEW

**Comment by rffontenelle** [comment]
@coby2023t What is exactly the error you're seeing?

**Comment by coby2023t** [comment]
the original setting is not working as is.

**Comment by rffontenelle** [comment]
FYI, `tx init` generates .tx/config with `https://app.transifex.com`. If the it is not correct, that should be changed as well.

```
$ tx init

Successful creation of '.tx/config' file
$ cat .tx/config 
[main]
host = https://app.transifex.com
$ tx --version
TX Client, version=1.6.11
```

**Comment by coby2023t** [comment]
checked, the README.md should stay it was, at line 124
[main]
host=https://app.transifex.com


Rafael Fontenelle ***@***.***> 於 2024年5月17日 週五 上午12:15寫道：

**Pull request closed without merging**
