### PR TITLE
Add cli update command

### PR DESCRIPTION
**Pull request by codegaze**
This adds a new command to self update the `tx` application with a few
arguments.

```
tx update -> If there is a new latest version shows a prompt to the user
in order to update

Flags:
--check: Just check if there is a new version.

--no-interactive: Runs update without prompt

--debug: Shows logs for the update process
```

**Note:** Tests created for this touch the github repo in order to get
information about the current release

**How to test:**
Way 1: Override the version argument in `main.go` build with `tx` as an executable name and test things 
Way 2: Build the executable with `-ldflags "-X github.com/transifex/cli/internal/txlib.Version=<version you want>"`.

### CODE REVIEW

**Comment by kostasgian** [comment]
1. Following the instructions, with Way 2, when giving i.e. `Version=v0.0.1`, the `v` in the version was creating an error when running the update command:
    ```
    $ ./bin/tx update --check
    ERROR   Invalid character(s) found in major number "v0"
    ```
    After removing the `v` letter the command was successful:
    ```
    $ ./bin/tx update --check
    There is a new latest release for you v0.0.1 -> v0.0.2
    ```

**Comment by kostasgian** [comment]
After checking for update after the update (I suppose this is happening because the versions are the same):
    ```
    $ ./bin/tx update --check
    No help topic for 'update'
    ```
    Maybe a better message would be appropriate, something like you have the latest version or something...

**Comment by kostasgian** [comment]
When updating with debug mode (`./bin/tx update --debug) in the interactive mode I get the question written down twice:
```
Do you want to update: y
Do you want to update: y
```
I am not asked twice, it is just written down two times.

**Review by kostasgian — APPROVED** [review]
LGTM

**Comment by codegaze** [comment]
> Following the instructions, with Way 2, when giving i.e. `Version=v0.0.1`, the `v` in the version was creating an error when running the update command:
> `$ ./bin/tx update --check ERROR Invalid character(s) found in major number "v0"`
> After removing the `v` letter the command was successful:
> `$ ./bin/tx update --check There is a new latest release for you v0.0.1 -> v0.0.2`

@kostasgian You are correct, it was bad documentation. There should not be a `v` at that point (version is added in the build process by goreleaser)

**Pull request merged**
